name: graphlib
version: 0.0.4
author: Richard Lincoln <r.w.lincoln@gmail.com>
description: A directed and undirected multi-graph library.
homepage: https://github.com/rwl/graphlib
dependencies:
  quiver: any
dev_dependencies:
  browser: any
  test: any
