name: graphlib
version: 0.0.4
author: Richard Lincoln <r.w.lincoln@gmail.com>
description: A directed and undirected multi-graph library.
homepage: https://github.com/rwl/graphlib
dependencies:
  browser: '>=0.10.0+2 <0.11.0'
  charted: '>=0.2.5 <1.0.0'
  protobuf: any
dev_dependencies:
  graphviz: any
  unittest: '>=0.11.4 <0.12.0'
