name: graphlib
version: 0.0.3
author: Richard Lincoln <r.w.lincoln@gmail.com>
description: A directed and undirected multi-graph library.
homepage: https://github.com/rwl/graphlib
dependencies:
  browser: '>=0.10.0+2 <0.11.0'
  charted: '>=0.0.9 <0.1.0'
dev_dependencies:
  unittest: '>=0.11.4 <0.12.0'
